version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo building the typescript project...
      - ./node_modules/.bin/tsc
      - cp package.json dist/
      - cp package-lock.json dist/
      - cp Procfile dist/
      - cp buildspec.yml dist/

