version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 19.8.1
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g typescript
  build:
    commands:
      - echo Building the TypeScript project...
      - tsc
artifacts:
  files:
    - "**/*"
  base-directory: "./dist" # assuming your tsconfig.json outputs to a 'dist' directory
