version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo installing source npm dependencies...
      - npm install
      - npm install -g typescript
  build:
    commands:
      - echo building the typescript project...
      - tsc && cp package.json dist/ && cp package-lock.json dist/ && cp Procfile dist/ && cp buildspec.yml dist/
artifacts:
  files:
    - "**/*"
  base-directory: "./dist" # assuming your tsconfig.json outputs to a 'dist' directory
