version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands: npm run build

artifacts:
  files:
    - dist/**/*
    - package.json
    - package-lock.json
    - Procfile
    - node_modules/**/*
